---
Library Management System
---

classDiagram
    class User{
        +firstName: string
        +lastName: string
        +fullName: string
        +id: int
    }

    note for User "fullName should be derived from firstName and lastName"

    class Book{
        +title: string
        +author: string
        +isbn: string
        +isCheckedOut: boolean
        +checkoutCount: int
        +ratings: List~Rating~
        +addToLibrary()
        +checkout()
        +return()
        +rate()
        +getAvearageRating()
    }

    class Library{
        +books: List~Book~$
        +getOverdueBooks()$
        +getBooksByAuthor()$
        +getBookdsByTitle()$
        +sort()$
        +save()$
        +load()$
    }