"use strict";

// we can inherit from the Error class and change name property of it and add other propertyies and make out custom errors

class LengthExcededError extends Error {
    constructor(message){
        super(message);
        this.name = 'LengthExcededError';
        this.EXPECTED_LENGTH = 3;
    }
}

try{
    let arr = [1, 2, 3, 4, 5];

    if (arr.length > 3){
        throw new LengthExcededError("The length of the array is more than expected");
    }
} catch(err) {
    console.log(err);

    // one of the advantage of inherting from the Error class is that if we use instance of Error it will give true
    console.log(err instanceof Error);  // true
    // so when in future if we make a new error that inherits from LengthExcededError then the errors generated by it can also be check like "err instaceof LengthExcededError"
}